# Generated by Django 5.1.14 on 2026-02-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotators", "0021_expert_expertise"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="annotatorexpertise",
            name="annotator_e_badge_e_idx",
        ),
        migrations.RemoveIndex(
            model_name="annotatorexpertise",
            name="annotator_e_test_to_idx",
        ),
        migrations.AlterField(
            model_name="annotatorexpertise",
            name="test_email_sent",
            field=models.BooleanField(
                default=False, help_text="Whether test invitation email has been sent"
            ),
        ),
        migrations.AlterField(
            model_name="annotatorexpertise",
            name="test_email_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="annotatorexpertise",
            name="test_token_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="expertprofile",
            name="minimum_payout",
            field=models.DecimalField(
                decimal_places=2,
                default=100.0,
                help_text="Minimum payout threshold in Credits",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="taskassignment",
            name="base_payment",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Base Credits × complexity",
                max_digits=10,
            ),
        ),
    ]
