# Generated by Django 5.1.14 on 2026-02-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0011_projectbilling_annotation_completed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditpackage",
            name="rate_per_credit",
            field=models.DecimalField(
                decimal_places=2, help_text="Price per credit in Credits", max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="extra_storage_rate_per_gb",
            field=models.DecimalField(
                decimal_places=2,
                default=15.0,
                help_text="Rate per GB per month for storage beyond free limit (in Credits)",
                max_digits=6,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="price_inr",
            field=models.DecimalField(
                decimal_places=2, help_text="Price in Credits", max_digits=10
            ),
        ),
    ]
